<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<TargetFramework>net7.0</TargetFramework>
    <RootNamespace>N_m3u8DL_RE</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- 
      When enabling LangVersion preview, that enables first class span's which then prefers MemoryExtensions.Contains over Enumerable.Contains
      See details: https://github.com/dotnet/runtime/issues/109757
    -->
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
	<Version>0.2.0</Version>
	<Platforms>AnyCPU;x64</Platforms>
	<Trimming>full</Trimming>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="5.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NiL.JS" Version="2.5.1600" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

</Project>
