//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N_m3u8DL_RE.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N_m3u8DL_RE.Common.Resource.ResString", typeof(ResString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 fMP4 is detected, binary merging is automatically enabled 的本地化字符串。
        /// </summary>
        public static string autoBinaryMerge {
            get {
                return ResourceManager.GetString("autoBinaryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dolby Vision content is detected, binary merging is automatically enabled 的本地化字符串。
        /// </summary>
        public static string autoBinaryMerge2 {
            get {
                return ResourceManager.GetString("autoBinaryMerge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unrecognized encryption method is detected, binary merging is automatically enabled 的本地化字符串。
        /// </summary>
        public static string autoBinaryMerge3 {
            get {
                return ResourceManager.GetString("autoBinaryMerge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad m3u8 的本地化字符串。
        /// </summary>
        public static string badM3u8 {
            get {
                return ResourceManager.GetString("badM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary merging... 的本地化字符串。
        /// </summary>
        public static string binaryMerge {
            get {
                return ResourceManager.GetString("binaryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verifying the validity of the last segment 的本地化字符串。
        /// </summary>
        public static string checkingLast {
            get {
                return ResourceManager.GetString("checkingLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Params of input Url to segments, useful for some websites, such as kakao.com 的本地化字符串。
        /// </summary>
        public static string cmd_appendUrlParams {
            get {
                return ResourceManager.GetString("cmd_appendUrlParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically selects the best tracks of all types 的本地化字符串。
        /// </summary>
        public static string cmd_autoSelect {
            get {
                return ResourceManager.GetString("cmd_autoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary merge 的本地化字符串。
        /// </summary>
        public static string cmd_binaryMerge {
            get {
                return ResourceManager.GetString("cmd_binaryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if the actual number of segments downloaded matches the expected number 的本地化字符串。
        /// </summary>
        public static string cmd_checkSegmentsCount {
            get {
                return ResourceManager.GetString("cmd_checkSegmentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full path to the tool used for MP4 decryption, like C:\Tools\mp4decrypt.exe 的本地化字符串。
        /// </summary>
        public static string cmd_decryptionBinaryPath {
            get {
                return ResourceManager.GetString("cmd_decryptionBinaryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete temporary files when done 的本地化字符串。
        /// </summary>
        public static string cmd_delAfterDone {
            get {
                return ResourceManager.GetString("cmd_delAfterDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full path to the ffmpeg binary, like C:\Tools\ffmpeg.exe 的本地化字符串。
        /// </summary>
        public static string cmd_ffmpegBinaryPath {
            get {
                return ResourceManager.GetString("cmd_ffmpegBinaryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass custom header(s) to server, Example:
        ///-H &quot;Cookie: mycookie&quot; -H &quot;User-Agent: iOS&quot; 的本地化字符串。
        /// </summary>
        public static string cmd_header {
            get {
                return ResourceManager.GetString("cmd_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Url or File 的本地化字符串。
        /// </summary>
        public static string cmd_Input {
            get {
                return ResourceManager.GetString("cmd_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass decryption key(s) to mp4decrypt/shaka-packager. format:
        ///--key KID1:KEY1 --key KID2:KEY2 的本地化字符串。
        /// </summary>
        public static string cmd_keys {
            get {
                return ResourceManager.GetString("cmd_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the kid-key file, the program will search the KEY with KID from the file.(Very large file are not recommended) 的本地化字符串。
        /// </summary>
        public static string cmd_keyText {
            get {
                return ResourceManager.GetString("cmd_keyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get KEY, ignore. 的本地化字符串。
        /// </summary>
        public static string cmd_loadKeyFailed {
            get {
                return ResourceManager.GetString("cmd_loadKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set log level 的本地化字符串。
        /// </summary>
        public static string cmd_logLevel {
            get {
                return ResourceManager.GetString("cmd_logLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrypt MP4 segments in real time 的本地化字符串。
        /// </summary>
        public static string cmd_MP4RealTimeDecryption {
            get {
                return ResourceManager.GetString("cmd_MP4RealTimeDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set output directory 的本地化字符串。
        /// </summary>
        public static string cmd_saveDir {
            get {
                return ResourceManager.GetString("cmd_saveDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set output filename 的本地化字符串。
        /// </summary>
        public static string cmd_saveName {
            get {
                return ResourceManager.GetString("cmd_saveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string cmd_savePattern {
            get {
                return ResourceManager.GetString("cmd_savePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip download 的本地化字符串。
        /// </summary>
        public static string cmd_skipDownload {
            get {
                return ResourceManager.GetString("cmd_skipDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip segments merge 的本地化字符串。
        /// </summary>
        public static string cmd_skipMerge {
            get {
                return ResourceManager.GetString("cmd_skipMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitle output format 的本地化字符串。
        /// </summary>
        public static string cmd_subFormat {
            get {
                return ResourceManager.GetString("cmd_subFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select only subtitle tracks 的本地化字符串。
        /// </summary>
        public static string cmd_subOnly {
            get {
                return ResourceManager.GetString("cmd_subOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically fix subtitles 的本地化字符串。
        /// </summary>
        public static string cmd_subtitleFix {
            get {
                return ResourceManager.GetString("cmd_subtitleFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set download thread count 的本地化字符串。
        /// </summary>
        public static string cmd_threadCount {
            get {
                return ResourceManager.GetString("cmd_threadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set temporary file directory 的本地化字符串。
        /// </summary>
        public static string cmd_tmpDir {
            get {
                return ResourceManager.GetString("cmd_tmpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set UI language 的本地化字符串。
        /// </summary>
        public static string cmd_uiLanguage {
            get {
                return ResourceManager.GetString("cmd_uiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Give these arguments to the URL Processors. 的本地化字符串。
        /// </summary>
        public static string cmd_urlProcessorArgs {
            get {
                return ResourceManager.GetString("cmd_urlProcessorArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use shaka-packager instead of mp4decrypt 的本地化字符串。
        /// </summary>
        public static string cmd_useShakaPackager {
            get {
                return ResourceManager.GetString("cmd_useShakaPackager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write meta json after parsed 的本地化字符串。
        /// </summary>
        public static string cmd_writeMetaJson {
            get {
                return ResourceManager.GetString("cmd_writeMetaJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetch:  的本地化字符串。
        /// </summary>
        public static string fetch {
            get {
                return ResourceManager.GetString("fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ffmpeg merging... 的本地化字符串。
        /// </summary>
        public static string ffmpegMerge {
            get {
                return ResourceManager.GetString("ffmpegMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ffmpeg not found, please download at: https://ffmpeg.org/download.html 的本地化字符串。
        /// </summary>
        public static string ffmpegNotFound {
            get {
                return ResourceManager.GetString("ffmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting TTML(raw) subtitle... 的本地化字符串。
        /// </summary>
        public static string fixingTTML {
            get {
                return ResourceManager.GetString("fixingTTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting TTML(mp4) subtitle... 的本地化字符串。
        /// </summary>
        public static string fixingTTMLmp4 {
            get {
                return ResourceManager.GetString("fixingTTMLmp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting VTT(raw) subtitle... 的本地化字符串。
        /// </summary>
        public static string fixingVTT {
            get {
                return ResourceManager.GetString("fixingVTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting VTT(mp4) subtitle... 的本地化字符串。
        /// </summary>
        public static string fixingVTTmp4 {
            get {
                return ResourceManager.GetString("fixingVTTmp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Processor matched 的本地化字符串。
        /// </summary>
        public static string keyProcessorNotFound {
            get {
                return ResourceManager.GetString("keyProcessorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live stream found 的本地化字符串。
        /// </summary>
        public static string liveFound {
            get {
                return ResourceManager.GetString("liveFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading URL:  的本地化字符串。
        /// </summary>
        public static string loadingUrl {
            get {
                return ResourceManager.GetString("loadingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master List detected, try parse all streams 的本地化字符串。
        /// </summary>
        public static string masterM3u8Found {
            get {
                return ResourceManager.GetString("masterM3u8Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content Matched: [white on mediumorchid1]Dynamic Adaptive Streaming over HTTP[/] 的本地化字符串。
        /// </summary>
        public static string matchDASH {
            get {
                return ResourceManager.GetString("matchDASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content Matched: [white on deepskyblue1]HTTP Live Streaming[/] 的本地化字符串。
        /// </summary>
        public static string matchHLS {
            get {
                return ResourceManager.GetString("matchHLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input not supported:  的本地化字符串。
        /// </summary>
        public static string notSupported {
            get {
                return ResourceManager.GetString("notSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing streams... 的本地化字符串。
        /// </summary>
        public static string parsingStream {
            get {
                return ResourceManager.GetString("parsingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [grey](Move up and down to reveal more streams)[/] 的本地化字符串。
        /// </summary>
        public static string promptChoiceText {
            get {
                return ResourceManager.GetString("promptChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Press [blue]&lt;space&gt;[/] to toggle a stream, [green]&lt;enter&gt;[/] to accept) 的本地化字符串。
        /// </summary>
        public static string promptInfo {
            get {
                return ResourceManager.GetString("promptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select [green]what you want to download[/]: 的本地化字符串。
        /// </summary>
        public static string promptTitle {
            get {
                return ResourceManager.GetString("promptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading media info... 的本地化字符串。
        /// </summary>
        public static string readingInfo {
            get {
                return ResourceManager.GetString("readingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to search for KEY from text file... 的本地化字符串。
        /// </summary>
        public static string searchKey {
            get {
                return ResourceManager.GetString("searchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segment count check not pass, total: {}, downloaded: {}. 的本地化字符串。
        /// </summary>
        public static string segmentCountCheckNotPass {
            get {
                return ResourceManager.GetString("segmentCountCheckNotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected streams: 的本地化字符串。
        /// </summary>
        public static string selectedStream {
            get {
                return ResourceManager.GetString("selectedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start downloading... 的本地化字符串。
        /// </summary>
        public static string startDownloading {
            get {
                return ResourceManager.GetString("startDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracted, there are {} streams, with {} basic streams, {} audio streams, {} subtitle streams 的本地化字符串。
        /// </summary>
        public static string streamsInfo {
            get {
                return ResourceManager.GetString("streamsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing meta.json 的本地化字符串。
        /// </summary>
        public static string writeJson {
            get {
                return ResourceManager.GetString("writeJson", resourceCulture);
            }
        }
    }
}
